# https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/
# uuid: custom-hot-corners-extended@G-dH.github.com
# src: https://extensions.gnome.org/extension-data/custom-hot-corners-extendedG-dH.github.com.v11.shell-extension.zip

- name: gnome | extension | custom-hot-corners-extended
  tags: gnome,extension,custom_hot_corners_extended
  ansible.builtin.include_tasks: _gnome-shell_extension.yml
  loop:
    - { name: "custom-hot-corners-extended", 
        flag: custom_hot_corners_extended,
        src: "https://extensions.gnome.org/extension-data/custom-hot-corners-extendedG-dH.github.com.v11.shell-extension.zip",
        uuid: "custom-hot-corners-extended@G-dH.github.com" }
  when: custom_hot_corners_extended is defined and custom_hot_corners_extended

- name: gnome | extension | custom-hot-corners-extended | settings misc
  tags: gnome,extension,custom_hot_corners_extended
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/custom-hot-corners-extended/misc/{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "corners-visible", value: "false" }
    - { key: "supported-active-extensions", value: "@as []" }
    - { key: "win-switch-wrap", value: "true" }
    - { key: "win-thumbnail-scale", value: "20" }
    - { key: "ws-switch-indicator-mode", value: "2" }
    - { key: "ws-switch-wrap", value: "true" }

- name: gnome | extension | custom-hot-corners-extended | actions
  tags: gnome,extension,custom_hot_corners_extended
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ item.where }}/action"
    value: "{{ item.value}}"
  with_items:
    - { where: "0-bottom-left-0", value: "'show-desktop-mon'" }
    - { where: "0-bottom-left-1", value: "'prefs'" }
    - { where: "0-bottom-left-2", value: "'recent-workspace'" }
    - { where: "0-bottom-left-3", value: "'disabled'" }
    - { where: "0-bottom-left-4", value: "'disabled'" }
    - { where: "0-bottom-left-5", value: "'disabled'" }
    - { where: "0-bottom-right-0", value: "'make-thumbnail-win'" }
    - { where: "0-bottom-right-1", value: "'disabled'" }
    - { where: "0-bottom-right-2", value: "'disabled'" }
    - { where: "0-bottom-right-3", value: "'remove-win-thumbnails'" }
    - { where: "0-bottom-right-4", value: "'disabled'" }
    - { where: "0-bottom-right-5", value: "'disabled'" }
    - { where: "0-top-left-0", value: "'show-applications'" }
    - { where: "0-top-left-1", value: "'app-switcher-popup-all'" }
    - { where: "0-top-left-2", value: "'disabled'" }
    - { where: "0-top-left-3", value: "'disabled'" }
    - { where: "0-top-left-4", value: "'disabled'" }
    - { where: "0-top-left-5", value: "'disabled'" }
    - { where: "0-top-right-0", value: "'toggle-overview'" }
    - { where: "0-top-right-1", value: "'app-switcher-popup-all'" }
    - { where: "0-top-right-2", value: "'disabled'" }
    - { where: "0-top-right-3", value: "'disabled'" }
    - { where: "0-top-right-4", value: "'disabled'" }
    - { where: "0-top-right-5", value: "'disabled'" }

- name: gnome | extension | custom-hot-corners-extended | actions - ctrl
  tags: gnome,extension,custom_hot_corners_extended
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ item.where }}/ctrl"
    value: "{{ item.value}}"
  with_items:
    - { where: "0-bottom-left-0", value: "false" }
    - { where: "0-bottom-left-1", value: "false" }
    - { where: "0-bottom-left-2", value: "false" }
    - { where: "0-bottom-left-3", value: "false" }
    - { where: "0-bottom-left-4", value: "false" }
    - { where: "0-bottom-left-5", value: "false" }
    - { where: "0-bottom-right-0", value: "true" }
    - { where: "0-bottom-right-1", value: "false" }
    - { where: "0-bottom-right-2", value: "false" }
    - { where: "0-bottom-right-3", value: "false" }
    - { where: "0-bottom-right-4", value: "false" }
    - { where: "0-bottom-right-5", value: "false" }
    - { where: "0-top-left-0", value: "false" }
    - { where: "0-top-left-1", value: "false" }
    - { where: "0-top-left-2", value: "false" }
    - { where: "0-top-left-3", value: "false" }
    - { where: "0-top-left-4", value: "false" }
    - { where: "0-top-left-5", value: "false" }
    - { where: "0-top-right-0", value: "false" }
    - { where: "0-top-right-1", value: "false" }
    - { where: "0-top-right-2", value: "false" }
    - { where: "0-top-right-3", value: "false" }
    - { where: "0-top-right-4", value: "false" }
    - { where: "0-top-right-5", value: "false" }
