---
- name: apt_update
  ansible.builtin.apt: update_cache=yes

- name: restart_sshd
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  ansible.builtin.file:
    path: /home/alex/.tmux/plugins
    owner: alex
    group: alex
    recurse: true

- name: update_vim_bundle_perms
  ansible.builtin.file:
    path: /home/alex/.vim/bundle
    owner: alex
    group: alex
    recurse: true
