# Load distro-specific variables
- name: workstation | include distribution variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: workstation | tasks
  block:
  ## User configs
  - name: workstation | import task | create user
    ansible.builtin.import_tasks: users/user.yml

  ## desktop environments
  - name: "workstation | include task | mate"
    ansible.builtin.include_tasks: "desktop_environments/mate/{{ inc_task }}.yml"
    when: mate is defined and mate == true
    with_items:
      # Do *NOT* sort these!
      - appearance
      - caja
      - keybindings
      - packages
      - peripherals
      - terminal
      - workspace_settings
    loop_control:
        loop_var: inc_task

  - name: "workstation | include task | gnome"
    ansible.builtin.include_tasks: "desktop_environments/gnome/{{ inc_task }}.yml"
    when: gnome is defined and gnome == true
    with_items:
      # Do *NOT* sort these!
      - appearance
      - keybindings
      - nautilus
      - packages
      - peripherals
      - shell_settings
      - terminal
      - tracker
    loop_control:
        loop_var: inc_task

  ## system setup
  - name: "workstation | include task | system setup"
    ansible.builtin.include_tasks: "system_setup/{{ inc_task }}.yml"
    with_items:
      # Do *NOT* sort these!
      - autofs 
      - scripts
      - tweaks
    loop_control:
        loop_var: inc_task

  ## install software
  - name: "workstation | include task | software"
    ansible.builtin.include_tasks: "software/{{ inc_task }}.yml"
    with_items:
      # These _may_ be sorted.
      - audacious
      - audacity
      - authy
      - aws_cli
      - azure_cli
      - bitwarden
      - boto
      - brave
      - caffeine
      - chromium
      - codecs
      - darktable
      - discord
      - firefox
      - foliate
      - glimpse
      - google_chrome
      - kdenlive
      - keepassxc
      - ksnip
      - libreoffice
      - linode_cli
      - lutris
      - mattermost
      - minecraft
      - misc_games
      - misc_packages
      - neovim
      - openshot
      - packer
      - podman
      - shutter
      - signal
      - solaar
      - spotify
      - steam
      - syncthing
      - teams
      - telegram
      - terraform
      - thunderbird
      - todoist
      - ulauncher
      - vagrant
      - virtualbox
      - vivaldi
      - vlc
      - vscode
      - xonotic
    loop_control:
      loop_var: inc_task
    when:
      - lookup('vars', inc_task, default=false)

  rescue:
    - set_fact: task_failed=true
