# Load distro-specific variables
- name: workstation | include distribution variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: workstation | tasks
  block:
  ## User configs
  - name: workstation | import task | create user alex
    ansible.builtin.import_tasks: users/alex.yml

  ## desktop environments
  - name: "workstation | import task | mate - {{ item }}"
    ansible.builtin.include_tasks: "desktop_environments/mate/{{ item }}.yml"
    when: mate is defined and mate == true
    loop:
      # Do *NOT* sort these!
      - appearance
      - caja
      - keybindings
      - packages
      - peripherals
      - terminal
      - workspace_settings

  - name: "workstation | import task | gnome - {{ item }}"
    ansible.builtin.include_tasks: "desktop_environments/gnome/{{ item }}.yml"
    when: gnome is defined and gnome == true
    loop:
      # Do *NOT* sort these!
      - appearance
      - keybindings
      - nautilus
      - packages
      - peripherals
      - shell_settings
      - terminal
      - tracker

  ## system setup
  - name: "workstation | import task | system setup - {{ item }}"
    ansible.builtin.include_tasks: "system_setup/{{ item }}.yml"
    loop:
      # Do *NOT* sort these!
      - autofs 
      - scripts
      - tweaks

  ## install software
  - name: "workstation | import task | software - {{ item }}"
    ansible.builtin.include_tasks: "software/{{ item }}.yml"
    loop:
      # These _may_ be sorted.
      - audacious
      - audacity
      - authy
      - aws_cli
      - azure_cli
      - bitwarden
      - boto
      - brave
      - caffeine
      - chromium
      - codecs
      - darktable
      - firefox
      - foliate
      - glimpse
      - google_chrome
      - kdenlive
      - keepassxc
      - libreoffice
      - linode-cli
      - lutris
      - mattermost
      - minecraft
      - misc_games
      - misc_packages
      - neovim
      - openshot
      - packer
      - signal
      - solaar
      - spotify
      - steam
      - syncthing
      - teams
      - terraform
      - thunderbird
      - todoist
      - ulauncher
      - vagrant
      - virtualbox
      - vivaldi
      - vlc
      - xonotic

  rescue:
    - set_fact: task_failed=true
