- name: users | alex | create group
  tags: groups,alex,users
  ansible.builtin.group:
    name: alex
    state: present

- name: users | alex | create user
  tags: alex,sudo,users
  ansible.builtin.user:
    name: alex
    group: alex
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "Alexander Skwar"
    shell: /bin/bash

- name: users | alex | alex | add sudoers file
  tags: alex,settings,sudo,system,users
  ansible.builtin.copy:
    src: users/sudoers_alex
    dest: /etc/sudoers.d/alex
    owner: root
    group: root
    mode: 0440

- name: users | alex | create .ssh directory
  tags: dotfiles,alex,ssh,users
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: alex
    group: alex
    mode: 0700
  with_items:
    - { dir: '/home/alex/.ssh' }

- name: users | alex | add public key
  tags: dotfiles,alex,ssh,ssh-keys,users
  authorized_key:
    user: alex
    key: "{{ item }}"
  with_file:
    - users/alex/ssh/alex_id_ed25519.pub

- name: users | alex | create config directories
  tags: dotfiles,alex,tmux,users,vim,zsh
  ansible.builtin.file:
    path: /home/alex/{{ item.dir }}
    state: directory
    owner: alex
    group: alex
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

- name: users | alex | copy tmux config (server version)
  tags: dotfiles,users,alex,tmux,users,vim,zsh
  ansible.builtin.copy:
    src: users/alex/tmux/tmux.conf.server
    dest: /home/alex/.tmux.conf
    owner: alex
    group: alex
    mode: 0600
  when: "'server' not in group_names"

- name: users | alex | copy tmux config (workstation version)
  tags: dotfiles,users,alex,tmux,users,vim,zsh
  ansible.builtin.copy:
    src: users/alex/tmux/tmux.conf.workstation
    dest: /home/alex/.tmux.conf
    owner: alex
    group: alex
    mode: 0600
  when: "'server' in group_names"

- name: users | alex | copy dotfiles
  tags: dotfiles,users,alex,tmux,users,vim,zsh
  ansible.builtin.copy:
    src: users/alex/{{ item.src }}
    dest: /home/alex/{{ item.dest }}
    owner: alex
    group: alex
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
    - { src: 'zsh/zshrc', dest: '.zshrc' }

- name: users | alex | clone tmux-completion plugin repository
  tags: dotfiles,alex,users,tmux
  ansible.builtin.git:
    repo: https://github.com/srsudar/tmux-completion.git
    dest: /home/alex/.tmux/plugins/completion
    force: yes
  notify: update_tmux_plugin_perms

- name: users | alex | clone tmux-continuum plugin repository
  tags: dotfiles,alex,users,tmux
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: /home/alex/.tmux/plugins/continuum
    force: yes
  notify: update_tmux_plugin_perms

- name: users | alex | clone tmux-resurrect plugin repository
  tags: dotfiles,alex,users,tmux
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: /home/alex/.tmux/plugins/resurrect
    force: yes
  notify: update_tmux_plugin_perms

- name: users | alex | copy individual zsh config files
  tags: dotfiles,alex,users,zsh
  ansible.builtin.copy:
    src: users/alex/zsh/{{ item.src }}
    dest: /home/alex/.zsh/{{ item.src }}
    owner: alex
    group: alex
    mode: 0600
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'bindkey.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'exports.zsh' }
    - { src: 'functions.zsh' }
    - { src: 'history.zsh' }
    - { src: 'path.zsh' }
    - { src: 'plugins.zsh' }
    - { src: 'prompt.zsh' }
    - { src: 'setopt.zsh' }
    - { src: 'theming.zsh' }

- name: users | alex | copy vim ftype files
  tags: dotfiles,alex,users,vim
  ansible.builtin.copy:
    src: users/alex/vim/{{ item.src }}
    dest: /home/alex/.vim/ftplugin/{{ item.src }}
    owner: alex
    group: alex
    mode: 0600
  with_items:
    - { src: 'cmake.vim' }
    - { src: 'cpp.vim' }
    - { src: 'html.vim' }
    - { src: 'perl.vim' }
    - { src: 'python.vim' }
    - { src: 'ruby.vim' }
    - { src: 'sql.vim' }
    - { src: 'xml.vim' }

- name: users | alex | copy vim color files
  tags: dotfiles,alex,users,vim
  ansible.builtin.copy:
    src: users/alex/vim/{{ item.src }}
    dest: /home/alex/.vim/colors/{{ item.src }}
    owner: alex
    group: alex
    mode: 0600
  with_items:
    - { src: 'bubblegum-256-dark.vim' }
    - { src: 'darktango.vim' }
    - { src: 'jellybeans.vim' }
    - { src: 'xoria256.vim' }
    - { src: 'zenburn.vim' }

- name: users | alex | install pathogen
  tags: dotfiles,alex,users,vim
  ansible.builtin.copy:
    src: users/alex/vim/{{ item.src }}
    dest: "{{ item.dest }}"
    owner: alex
    group: alex
    mode: 0700
  with_items:
    - { src: 'pathogen.vim', dest: '/home/alex/.vim/autoload/pathogen.vim' }

- name: users | alex | checkout git repositories
  tags: git,users,alex
  become: yes
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '/home/alex/.vim/bundle/ctrlp.vim' }
    - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '/home/alex/.vim/bundle/jedi-vim' }
    - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '/home/alex/.vim/bundle/ansible-vim' }
    - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '/home/alex/.vim/bundle/vim-grammarous' }
    - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '/home/alex/.vim/bundle/thesaurus_query' }
    - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '/home/alex/.vim/bundle/nerdtree' }
    - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '/home/alex/.vim/bundle/vim-obsession' }
    - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '/home/alex/.vim/bundle/syntastic' }
  notify: update_vim_bundle_perms
