- name: software | audacious | install package
  tags: packages,flatpak,audacious,workstation-packages
  become_user: alex
  community.general.flatpak:
    name: org.atheme.audacious
    method: user
    state: present
  when: audacious is defined and audacious == true
