# note: snap packages not automated in arch yet, snapd is not available in repo
- name: software | authy | install package
  tags: packages,authy,snap,workstation-packages
  community.general.snap:
    name:  authy
    channel: latest/edge
    state: present
  when:
    - ansible_distribution != "Archlinux"
    - authy is defined
    - authy == true

- name: software | authy | enable autostart
  tags: packages,authy,snap,workstation-packages
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/authy_authy.desktop
    dest: /home/alex/.config/autostart/authy.desktop
    owner: alex
    ansible.builtin.group: alex
    state: link
  when:
    - ansible_distribution != "Archlinux"
    - authy is defined
    - authy == true
