- name: software | authy | enable/disable autostart
  tags: packages,authy,snap,workstation-packages
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/authy_authy.desktop
    dest: /home/{{ user_name }}/.config/autostart/authy.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: "{{ authy | ternary('link', 'absent')}}"
  when:
    - ansible_distribution != "Archlinux"
    - authy is defined
