- name: software | azure cli | add repository key
  tags: packages,azure-cli,workstation-packages
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  when:
    - ansible_os_family == "Debian"
    - azure_cli is defined
    - azure_cli == true

- name: software | azure cli | add repository
  tags: packages,azure-cli,workstation-packages
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    filename: azure-cli
  register: azure_cli_repo
  when:
    - ansible_os_family == "Debian"
    - azure_cli is defined
    - azure_cli == true

- name: software | azure cli | update sources (repo added or changed)
  tags: packages,azure-cli,workstation-packages
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when:
    - ansible_os_family == "Debian"
    - azure_cli is defined
    - azure_cli == true
    - azure_cli_repo.changed

- name: software | azure cli | install package
  tags: packages,azure-cli,workstation-packages
  ansible.builtin.apt:
    name: azure-cli
  when:
    - ansible_os_family == "Debian"
    - azure_cli is defined
    - azure_cli == true
