- name: software | bitwarden | install package
  tags: bitwarden,packages,flatpak,workstation-packages
  become_user: "{{ user_name }}"
  community.general.flatpak:
    name: com.bitwarden.desktop
    method: user
    state: present
  when: bitwarden is defined and bitwarden == true
