- name: software | brave | add repository key
  tags: packages,brave,workstation-packages
  ansible.builtin.apt_key:
    url: "https://brave-browser-apt-{{ item }}.s3.brave.com/brave-browser-{{ item }}-archive-keyring.gpg"
    state: present
  loop: "{{ brave }}"
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - brave is defined

- name: software | brave | add repository
  tags: packages,brave,workstation-packages
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-{{ item }}.s3.brave.com/ stable main"
    state: present
    filename: "brave-browser-{{ item }}"
  loop: "{{ brave }}"
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - brave is defined

- name: software | brave | install package
  tags: packages,brave,workstation-packages
  ansible.builtin.apt:
    name: "brave-browser-{{ item }}"
    state: latest
  loop: "{{ brave }}"
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - brave is defined
