- name: software | chromium | install distro package (arch)
  tags: packages,chromium,snap,workstation-packages
  ansible.builtin.package:
    name: chromium
    state: "{{ (packages | selectattr('name', 'equalto', 'chromium') | first).state in ['false', 'absent', 'no', false]) | ternary('absent', 'present') }}"
  when:
    - ansible_distribution == "Archlinux"
