# Force remove apt...
- name: software | flameshot | remove apt package
  ansible.builtin.apt:
    name: flameshot
    purge: yes
    state: absent
  when:
    - packages | selectattr('name', 'equalto', 'flameshot') != []
    - (packages | selectattr('name', 'equalto', 'flameshot') | first).state not in ['false', 'absent', 'no', false]

# ...and snap package
- name: software | flameshot | remove snap package
  tags: packages,snap,flameshot,workstation-packages
  community.general.snap:
    name: flameshot
    # channel: latest/edge
    state: absent
  when:
    - ansible_distribution != "Archlinux"
    - packages | selectattr('name', 'equalto', 'flameshot') != []
    - (packages | selectattr('name', 'equalto', 'flameshot') | first).state not in ['false', 'absent', 'no', false]

- name: software | flameshot | install/remove appimage package
  tags: apps,flameshot,appimage,software,workstation-packages
  ansible.builtin.include_tasks: "_appimage_pkg.yml"
  when:
    - packages | selectattr('name', 'equalto', 'flameshot') != []
    - (packages | selectattr('name', 'equalto', 'flameshot') | first).state not in ['false', 'absent', 'no', false]
  vars:
    package: {
      name: flameshot,
      flag: flameshot,
      url: https://github.com/flameshot-org/flameshot/releases/download/v0.10.2/Flameshot-0.10.2.x86_64.AppImage,
      dest: .local/bin/flameshot
    }
