- name: software | google-chrome | add repository key
  tags: packages,google-chrome,workstation-packages
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - google_chrome is defined
    - google_chrome == true

- name: software | google-chrome | add repository
  tags: packages,google-chrome,workstation-packages
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
  register: chrome_repo
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - google_chrome is defined
    - google_chrome == true

- name: software | google-chrome | update sources (repo added or changed)
  tags: packages,google-chrome,workstation-packages
  ansible.builtin.apt:
    update_cache: yes
  changed_when: False
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - google_chrome is defined
    - google_chrome == true
    - chrome_repo.changed

- name: software | google-chrome | install package
  tags: packages,google-chrome,workstation-packages
  ansible.builtin.apt:
    name: google-chrome-stable
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - google_chrome is defined
    - google_chrome == true
