- name: software | kdenlive | copy launcher
  tags: apps,appimage,software,kdenlive
  ansible.builtin.template:
    src: users/USER/kdenlive.desktop
    dest: /home/{{ user_name }}/.local/share/applications/kdenlive.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700
  when:
    - kdenlive is defined
    - kdenlive == true

- name: software | kdenlive | install package
  ansible.builtin.get_url:
    url: https://download.kde.org/stable/kdenlive/20.08/linux/kdenlive-20.08.2-x86_64.appimage
    dest: /home/{{ user_name }}/bin/kdenlive.app
    mode: '0700'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when:
    - kdenlive is defined
    - kdenlive == true
