- name: software | kdenlive | copy launcher
  tags: apps,appimage,software,kdenlive
  ansible.builtin.copy:
    src: users/alex/kdenlive.desktop
    dest: /home/alex/.local/share/applications/kdenlive.desktop
    owner: alex
    group: alex
    mode: 0700
  when:
    - kdenlive is defined
    - kdenlive == true

- name: software | kdenlive | install package
  ansible.builtin.get_url:
    url: https://download.kde.org/stable/kdenlive/20.08/linux/kdenlive-20.08.2-x86_64.appimage
    dest: /home/alex/bin/kdenlive.app
    mode: '0700'
    owner: alex
    group: alex
  when:
    - kdenlive is defined
    - kdenlive == true
