- name: software | keepassxc | enable autostart
  tags: packages,keepassxc,flatpak,workstation-packages
  ansible.builtin.file:
    src: /home/{{ user_name }}/.local/share/flatpak/exports/share/applications/org.keepassxc.KeePassXC.desktop
    dest: /home/{{ user_name }}/.config/autostart/org.keepassxc.KeePassXC.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: "{{ (packages | selectattr('name', 'equalto', 'keepassxc') | first).state in ['false', 'absent', 'no', false]) | ternary('absent', 'link') }}"

- name: software | keepassxc | create keepassxc install directory
  tags: packages,keepassxc,flatpak,workstation-packages
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/keepassxc
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'
  when: (packages | selectattr('name', 'equalto', 'keepassxc') | first).state not in ['false', 'absent', 'no', false])

# - name: software | keepassxc | add initial keepassxc config
#   tags: packages,keepassxc,flatpak,workstation-packages
#   ansible.builtin.copy:
#     src: users/USER/keepassxc.ini
#     dest: /home/{{ user_name }}/.config/keepassxc/keepassxc.ini
#     owner: "{{ user_name }}"
#     group: "{{ user_name }}"
#     mode: 0600
#   when: keepassxc is defined and keepassxc == true
