- name: software | keepassxc | install package
  tags: packages,firefox,flatpak,workstation-packages
  become_user: alex
  community.general.flatpak:
    name: org.keepassxc.KeePassXC
    method: user
    state: present

- name: software | keepassxc | enable autostart
  tags: packages,keepassxc,flatpak,workstation-packages
  ansible.builtin.file:
    src: /home/alex/.local/share/flatpak/exports/share/applications/org.keepassxc.KeePassXC.desktop
    dest: /home/alex/.config/autostart/org.keepassxc.KeePassXC.desktop
    owner: alex
    ansible.builtin.group: alex
    state: link

- name: software | keepassxc | create keepassxc install directory
  tags: packages,keepassxc,flatpak,workstation-packages
  ansible.builtin.file:
    path: /home/alex/.config/keepassxc
    state: directory
    owner: alex
    ansible.builtin.group: alex
    mode: 0700
  register: keepassxc_config_dir
  when: keepassxc is defined and keepassxc == true

- name: software | keepassxc | add initial keepassxc config
  tags: packages,keepassxc,flatpak,workstation-packages
  ansible.builtin.copy:
    src: users/alex/keepassxc.ini
    dest: /home/alex/.config/keepassxc/keepassxc.ini
    owner: alex
    ansible.builtin.group: alex
    mode: 0600
  when: keepassxc is defined and keepassxc == true
