- name: software | keybase | add repository key
  tags: packages,keybase,workstation-packages
  ansible.builtin.apt_key:
    url: https://keybase.io/docs/server_security/code_signing_key.asc
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - keybase is defined
    - keybase == true

- name: software | keybase | add repository
  tags: packages,keybase,workstation-packages
  ansible.builtin.apt_repository:
    repo: "deb http://prerelease.keybase.io/deb stable main"
    filename: google-chrome
  register: chrome_repo
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - keybase is defined
    - keybase == true

- name: software | keybase | update sources (repo added or changed)
  tags: packages,keybase,workstation-packages
  ansible.builtin.apt:
    update_cache: yes
  changed_when: False
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - keybase is defined
    - keybase == true
    - keybase_repo.changed

- name: software | keybase | install package (Debian)
  tags: packages,keybase,workstation-packages
  ansible.builtin.apt:
    name: keybase
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - keybase is defined
    - keybase == true

- name: software | keybase | install package (Archlinux)
  tags: packages,keybase,workstation-packages
  ansible.builtin.package:
    state: latest
    name: keybase-bin
  when:
    - ansible_distribution in ["Archlinux"]
    - keybase is defined
    - keybase == true
