# TBD: https://keybase.io/docs/the_app/install_linux
# Install a deb which sets up repo? No!

# - name: software | keybase | install ppa
#   tags: packages,keybase,workstation-packages
#   ansible.builtin.apt_repository:
#     repo: ???
#     state: present
#   when:
#     - ansible_distribution in ["Pop!_OS", "Ubuntu"]
#     - keybase is defined
#     - keybase == true

# - name: software | lutris | install package Debian
#   tags: packages,keybase,workstation-packages
#   ansible.builtin.package:
#     state: latest
#     name: keybase
#   when:
#     - ansible_distribution in ["Pop!_OS", "Ubuntu"]
#     - keybase is defined
#     - keybase == true

- name: software | lutris | install package Archlinux
  tags: packages,keybase,workstation-packages
  ansible.builtin.package:
    state: latest
    name: keybase-bin
  when:
    - ansible_distribution in ["Archlinux"]
    - keybase is defined
    - keybase == true
