- name: software | minecraft | install package
  tags: packages,flatpak,minecraft,gaming
  become_user: alex
  community.general.flatpak:
    name: com.mojang.Minecraft
    method: user
    state: present
  when: minecraft is defined and minecraft == true
