- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  ansible.builtin.package:
    name: "{{ misc_packages }}"

- name: software | install system packages specific to debian and ubuntu
  tags: packages,system,system-packages,workstation-packages
  ansible.builtin.package:
    name:
      - synaptic
      #- vim-gtk3
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  ansible.builtin.package:
    state: absent
    name:
      - firefox*
      - libreoffice-base-core
      - libreoffice-calc
      - libreoffice-common
      - libreoffice-core
      - libreoffice-draw
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-impress
      - libreoffice-math
      - libreoffice-writer
      - thunderbird*
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
