- name: software | openshot | install package
  tags: apps,openshot,appimage,software,workstation-packages
  ansible.builtin.get_url:
    url: https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.AppImage
    dest: /home/{{ user_name }}/bin/openshot.app
    mode: '0700'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when:
    - (packages | selectattr('name', 'equalto', 'openshot') | first).state not in ['false', 'absent', 'no', false])

- name: software | openshot | remove files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /home/{{ user_name }}/bin/openshot.app
  when:
    - (packages | selectattr('name', 'equalto', 'openshot') | first).state in ['false', 'absent', 'no', false])
