- name: software | openshot | install/remove appimage package
  tags: apps,openshot,appimage,software,workstation-packages
  ansible.builtin.include_tasks: "_appimage_pkg.yml"
  vars:
    package: {
      name: openshot,
      flag: openshot,
      url: https://github.com/OpenShot/openshot-qt/releases/download/v2.6.1/OpenShot-v2.6.1-x86_64.AppImage,
      dest: bin/openshot.app
    }
