- name: software | openshot | install package
  tags: apps,openshot,appimage,software,workstation-packages
  ansible.builtin.get_url:
    url: https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.AppImage
    dest: /home/alex/bin/openshot.app
    mode: '0700'
    owner: alex
    group: alex
  when:
    - openshot is defined
    - openshot == true
