- name: software | packer | install binary
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  when:
    - (packages | selectattr('name', 'equalto', 'packer') | first).state not in ['false', 'absent', 'no', false])
