- name: software | signal | enable autostart
  tags: packages,flatpak,signal,workstation-packages
  ansible.builtin.file:
    src: "/home/{{ user_name }}/.local/share/flatpak/exports/share/applications/org.signal.Signal.desktop"
    dest: "/home/{{ user_name }}/.config/autostart/org.signal.Signal.desktop"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: "{{ (packages | selectattr('name', 'equalto', 'mattermost') | first).state in ['false', 'absent', 'no', false]) | ternary('absent', 'link') }}"
