- name: software | solaar | make sure solaar doesn't autostart
  tags: packages,solaar,workstation-packages
  ansible.builtin.file:
    path: /etc/xdg/autostart/solaar.desktop
    state: absent
  when:
    - (packages | selectattr('name', 'equalto', 'solaar') | first).state not in ['false', 'absent', 'no', false])
