# add syncthing-controlled directories
- name: software | syncthing | create directories
  tags: syncthing
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700
  with_items:
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: templates }
  when: syncthing is defined and syncthing == true

- name: software | syncthing | copy .stignore file to synced directories
  tags: syncthing
  ansible.builtin.copy:
    src: users/USER/stignore
    dest: /home/{{ user_name }}/{{ item.dir }}/.stignore
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  with_items:
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: templates }
  when: syncthing is defined and syncthing == true

# syncthing repository for debian and ubuntu
- name: software | syncthing | install apt key
  tags: syncthing
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - syncthing is defined
    - syncthing == true

- name: software | syncthing | install repository
  tags: syncthing
  ansible.builtin.apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - syncthing is defined
    - syncthing == true

- name: software | syncthing | install syncthing packages
  tags: syncthing
  ansible.builtin.package:
    name:
      - syncthing
      #- syncthing-gtk
    state: latest
  register: syncthing_installed
  when:
    - syncthing is defined
    - syncthing == true

#- name: software | syncthing | add .desktop file for autostarting syncthing-gtk
#  tags: syncthing
#  ansible.builtin.copy:
#    src: users/USER/syncthing-gtk.desktop
#    dest: /home/{{ user_name }}/.config/autostart/syncthing-gtk.desktop
#    owner: "{{ user_name }}"
#    ansible.builtin.group: "{{ user_name }}"
#    mode: 0600
#  when:
#    - syncthing is defined
#  - syncthing == true

#- name: software | syncthing | ensure syncthing-gtk config folder exists
#  tags: syncthing
#  ansible.builtin.file:
#    path: /home/{{ user_name }}/.config/syncthing-gtk
#    state: directory
#    owner: "{{ user_name }}"
#    ansible.builtin.group: "{{ user_name }}"
#    mode: 0700
#  when:
#   - syncthing is defined
#    - syncthing == true

#- name: software | syncthing | add initial configuration file for syncthing-gtk
#  tags: syncthing
#  ansible.builtin.copy:
#    src: users/USER/syncthing_config.json
#    dest: /home/{{ user_name }}/.config/syncthing-gtk/config.json
#    owner: "{{ user_name }}"
#    ansible.builtin.group: "{{ user_name }}"
#    mode: 0600
#  when:
#    - syncthing is defined
#    - syncthing == true

# Enable and start syncthing
# Note: Not using systemd module because it triggers a dbus error due to no session while user is not logged in
- name: software | syncthing | start and enable syncthing
  tags: syncthing
  ansible.builtin.command: "{{ item }}"
  with_items:
    - systemctl enable syncthing@{{ user_name }}
    - systemctl restart syncthing@{{ user_name }}
  when: syncthing_installed.changed

# Adjust configuration file
- name: software | syncthing | pause to ensure config file exists
  tags: syncthing
  become_user: "{{ user_name }}"
  wait_for:
    path: /home/{{ user_name }}/.config/syncthing/config.xml
    delay: 10
  when: syncthing_installed.changed

- name: software | syncthing | config.xml - disable browser
  tags: syncthing
  become_user: "{{ user_name }}"
  ansible.builtin.replace:
    path: /home/{{ user_name }}/.config/syncthing/config.xml
    regexp: "<startBrowser>true</startBrowser>"
    ansible.builtin.replace: "<startBrowser>false</startBrowser>"
  notify: restart_syncthing
  when:
    - syncthing is defined
    - syncthing == true

- name: software | syncthing | config.xml - set ui theme
  tags: syncthing
  become_user: "{{ user_name }}"
  ansible.builtin.replace:
    path: /home/{{ user_name }}/.config/syncthing/config.xml
    regexp: "<theme>default</theme>"
    ansible.builtin.replace: "<theme>dark</theme>"
  notify: restart_syncthing
  when:
    - syncthing is defined
    - syncthing == true

- name: software | syncthing | remove default sync directory (~/Sync) from host
  tags: syncthing
  ansible.builtin.file:
    path: /home/{{ user_name }}/Sync
    state: absent
