- name: software | terraform | install binary
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  when:
    - packages | selectattr('name', 'equalto', 'terraform') != []
    - (packages | selectattr('name', 'equalto', 'terraform') | first).state not in ['false', 'absent', 'no', false]
    - ansible_distribution not in ["Pop!_OS", "Ubuntu"]

- name: software | terraform | remove old binary
  ansible.builtin.file:
    path: /usr/local/bin/terraform
    state: absent
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
