
- name: software | thunderbird | enable autostart
  tags: packages,flatpak,thunderbird,workstation-packages
  ansible.builtin.file:
    src: /home/{{ user_name }}/.local/share/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop
    dest: /home/{{ user_name }}/.config/autostart/org.mozilla.Thunderbird.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
  when: thunderbird is defined and thunderbird == true
