
- name: software | thunderbird | enable autostart
  tags: packages,flatpak,thunderbird,workstation-packages
  ansible.builtin.file:
    src: /home/{{ user_name }}/.local/share/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop
    dest: /home/{{ user_name }}/.config/autostart/org.mozilla.Thunderbird.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
  when:
    - packages | selectattr('name', 'equalto', 'thunderbird') != []
    - (packages | selectattr('name', 'equalto', 'thunderbird') | first).state not in ['false', 'absent', 'no', false]

- name: software | thunderbird | remove files
  tags: packages,flatpak,thunderbird,workstation-packages
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /home/{{ user_name }}/.config/autostart/org.mozilla.Thunderbird.desktop
  when:
    - (packages | selectattr('name', 'equalto', 'thunderbird') == []) or ((packages | selectattr('name', 'equalto', 'thunderbird') | first).state in ['false', 'absent', 'no', false])
