# note: snap packages not automated in arch yet, snapd is not available in repo
- name: software | todoist | install package
  tags: packages,snap,todoist,workstation-packages
  community.general.snap:
    name: todoist
    state: present
  when:
    - ansible_distribution != "Archlinux"
    - todoist is defined
    - todoist == true

- name: software | todoist | enable autostart
  tags: packages,todoist,snap,workstation-packages
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/todoist_todoist.desktop
    dest: /home/{{ user_name }}/.config/autostart/todoist_todoist.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
  when:
    - ansible_distribution != "Archlinux"
    - todoist is defined
    - todoist == true
