- name: software | todoist | enable autostart
  tags: packages,todoist,snap,workstation-packages
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/todoist_todoist.desktop
    dest: /home/{{ user_name }}/.config/autostart/todoist_todoist.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: "{{ (packages | selectattr('name', 'equalto', 'todoist') | first).state in ['false', 'absent', 'no', false]) | ternary('absent', 'link') }}"
  when:
    - ansible_distribution != "Archlinux"
