# Load distro-specific variables
- name: server | include distribution variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: server | tasks
  block:
  - name: "server | import task | {{ item }}"
    ansible.builtin.import_tasks: "{{ item }}.yml"
    loop:
      # May be sorted.
      - nrpe
      - ufw
      - qemu-agent

  - name: server | import task | unattended upgrades (Debian)
    ansible.builtin.include_tasks: unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true

  rescue:
    - set_fact: task_failed=true
