- name: gnome | nautilus | enable tree-view in nautilus
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/list-view/use-tree-view"
    value: "true"

- name: gnome | nautilus | set list view in nautilus
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"

- name: gnome | nautilus | configure double-click to open files
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/click-policy"
    value: "'double'"

- name: gnome | nautilus | set executable text activation
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/executable-text-activation"
    value: "'launch'"

- name: gnome | nautilus | enable option to permanently delete files
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/show-delete-permanently"
    value: "true"

- name: gnome | nautilus | enable option to create links
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/show-create-link"
    value: "true"

- name: gnome | nautilus | set directories to be shown before files in nautilus
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gtk/settings/file-chooser/sort-directories-first"
    value: "true"

- name: gnome | nautilus | configure icon-view in nautilus
  tags: gnome,nautilus
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/icon-view/captions"
    value: "['recency', 'size', 'type']"
