- name: system setup | development packages | install packages
  tags: dev,development,packages,python,ruby
  ansible.builtin.package:
    name:
      - git
      - perl
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
      - ruby
      - "{{ ruby_rake_package }}"
    state: latest

- name: system setup | development packages | remove packages
  tags: dev,development,packages,python,ruby
  ansible.builtin.package:
    name:
      - fabric
      - flake8
      - "{{ python_flake8_package }}"
      - "{{ python_pyflakes_package }}"
      - tig
    state: absent
