- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    state: latest
    name:
      - "{{ dns_utils_package}}"
      - apt-transport-https
      - at
      - colordiff
      - curl
      - fish
      - htop
      - iotop
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - ripgrep
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - wget
      - whois
      - zsh

- name: system setup | utilities | remove utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    state: absent
    name:
      - "{{ lm_sensors_package }}"
      - "{{ nfs_client_package }}"
      - "{{ rename_package }}"
      - "{{ vim_package }}"
      - mc
      - mosh
      - ranger

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  community.general.pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
