- name: system setup | repositories | add ignored packages for archlinux hosts
  tags: packages,repositories
  ansible.builtin.lineinfile:
      dest: /etc/pacman.conf
      regexp: "^#?IgnorePkg"
      line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers"
  when: ansible_distribution == "Archlinux"

- name: system setup | repositories | add sources.list for debian hosts
  tags: non-free,repositories
  ansible.builtin.copy:
    src: distribution_packages/debian_sources.list
    dest: /etc/apt/sources.list
    backup: yes
  notify: apt_update
  when: ansible_distribution == "Debian"

- name: system setup | repositories | add debian-backports
  tags: backports,repositories
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    filename: debian-backports
  notify: apt_update
  when: ansible_distribution == "Debian"

- name: system setup | repositories | install package management tools (debian-based)
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: system setup | fish shell | add repository
  tags: packages,repositories,system
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
    filename: fish-shell
  register: fish_shell_repo
  when: ansible_os_family == "Debian"

- name: system setup | fish shell | update sources (repo added or changed)
  tags: packages,repositories,system
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when:
    - ansible_os_family == "Debian"
    - fish_shell_repo.changed
