flatpaks:
  - {name: darktable, pkg: org.darktable.Darktable}
  - {name: discord, pkg: com.discordapp.Discord}
  - {name: minecraft, pkg: com.mojang.Minecraft}
  - {name: foliate, pkg: com.github.johnfactotum.Foliate}
  - {name: mattermost, pkg: com.mattermost.Desktop}
  - {name: spotify, pkg: com.spotify.Client}
  - {name: teams, pkg: com.microsoft.Teams}
  - {name: thunderbird, pkg: org.mozilla.thunderbird}
  - {name: xonotic, pkg: org.xonotic.Xonotic}
  - {name: audacity, pkg: org.audacityteam.Audacity}
  - {name: audacious, pkg: org.atheme.audacious}
  - {name: bitwarden, pkg: com.bitwarden.desktop}
  - {name: firefox, pkg: org.mozilla.firefox}
  - {name: glimpse, pkg: org.glimpse_editor.Glimpse}
  - {name: ksnip, pkg: org.ksnip.ksnip}
  - {name: keepassxc, pkg: org.keepassxc.KeePassXC}
  - {name: libreoffice, pkg: org.libreoffice.LibreOffice}
  - {name: signal, pkg: org.signal.Signal}
  - {name: desktop, pkg: org.telegram.desktop}
  - {name: vlc, pkg: org.videolan.VLC}

pips:
  - {name: linode_cli, pkg: linode-cli}
  - {name: boto, pkg: boto}

snaps:
  - {name: authy, channel: latest/edge}
  - {name: todoist}

generic_packages:
  - {name: solaar, pkg: solaar}
  # - caffeine
  - {name: gstreamer_libav_package, pkg: lookup('vars', gstreamer_libav_package)}
  - {name: gstreamer_plugins_bad_package, pkg: lookup('vars', gstreamer_plugins_bad_package)}
  - {name: docker_compose, pkg: docker-compose}

packages_games_remove:
  - chromium-bsu
  - extremetuxracer
  - frozen-bubble
  - gnome-chess
  - "{{ nethack_package }}"
  - supertux
  - supertuxkart
  - wesnoth

apts:
  - {name: azure_cli, key_url: https://packages.microsoft.com/keys/microsoft.asc, repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ (ansible_distribution_release == 'impish') | ternary('hirsute', ansible_distribution_release) }} main", pkg: azure-cli}
  - {name: brave-beta, key_url: "https://brave-browser-apt-beta.s3.brave.com/brave-browser-beta-archive-keyring.gpg", repo: "deb [arch=amd64] https://brave-browser-apt-beta.s3.brave.com/ stable main", pkg: "brave-browser-beta"}
  - {name: chrome-stable, key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub, repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main", pkg: google-chrome-stable}
  - {name: edga-beta, key_url: "https://packages.microsoft.com/keys/microsoft.asc", repo: "deb [arch=amd64] https://packages.microsoft.com/repos/edge/ stable main", repo_file: "microsoft-edge-beta", pkg: "microsoft-edge-beta"}
  - {name: keybase, key_url: https://keybase.io/docs/server_security/code_signing_key.asc, repo: "deb http://prerelease.keybase.io/deb stable main", pkg: keybase}
  - {name: lutris, repo: "ppa:lutris-team/lutris", pkg: lutris}
  - {name: neovim, repo: "ppa:neovim-ppa/stable", pkg: neovim}
  - {name: podman, key_url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ (ansible_distribution == 'Ubuntu') | ternary('xUbuntu', ansible_distribution) }}_{{ (ansible_distribution_release == 'impish') | ternary('21.04', ansible_distribution_version) }}/Release.key", repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ (ansible_distribution == 'Ubuntu') | ternary('xUbuntu', ansible_distribution) }}_{{ (ansible_distribution_release == 'impish') | ternary('21.04', ansible_distribution_version) }}/ /", pkg: podman}
  - {name: shutter, repo: ppa:shutter/ppa, pkg: shutter}
  - {name: ulauncher, repo: ppa:agornostal/ulauncher, pkg: ulauncher}
  - {name: virtualbox, key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc, repo: "deb https://download.virtualbox.org/virtualbox/debian buster contrib", pkg: "{{ virtualbox_package }}"}
  - {name: vivaldi-stable, key_url: https://repo.vivaldi.com/stable/linux_signing_key.pub, repo: "deb https://repo.vivaldi.com/stable/deb/ stable main", pkg: vivaldi-stable}
  - {name: vscode, key_url: https://packages.microsoft.com/keys/microsoft.asc, repo: "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main", pkg: code}

misc_packages:
  - acpid
  - alsa-utils
  - arandr
  - asunder
  - cifs-utils
  - "{{ cups_package }}"
  - "{{ cryptsetup_package }}"
  - dconf-editor
  - dialog
  - easytag
  - exfat-utils
  - "{{ font_fira_mono_package }}"
  - "{{ font_hack_ttf_package }}"
  - "{{ font_inconsolata_package }}"
  - "{{ font_noto_emoji_package }}"
  - "{{ font_terminus_package }}"
  #- geany
  - gparted
  - "{{ hunspell_package }}"
  - "{{ hyphen_package }}"
  - jq
  - "{{ p7zip_package }}"
  - "{{ libnotify_package }}"
  - meld
  - "{{ mpv_package}}"
  - "{{ network_manager_openconnect_package }}"
  - "{{ network_manager_openvpn_package }}"
  - "{{ network_manager_package }}"
  - "{{ network_manager_pptp_package }}"
  - "{{ network_manager_vpnc_package }}"
  - pavucontrol
  - resolvconf
  - shotwell
  - simplescreenrecorder
  - smbclient
  - sshpass
  - "{{ ssh_askpass_package }}"
  - terminator
  - transmission-gtk
  - unrar
  - "{{ wireguard_package }}"
  - "{{ wireless_tools_package }}"
  - "{{ wpa_supplicant_package }}"
  - xserver-xorg-input-synaptics
  - xsel
  #- x2goclient
