- name: software | todoist | enable autostart
  tags: packages,todoist,snap,workstation-packages
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/todoist_todoist.desktop
    dest: /home/{{ user_name }}/.config/autostart/todoist_todoist.desktop
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
  when:
    - ansible_distribution != "Archlinux"
    - todoist is defined
    - todoist == true
