- name: system setup | locale
  tags: locale,system,setup
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales|flatten(levels=1) }}"
  register: locale

- name: system setup | locale | set first locale as default locale
  tags: locale,system,setup
  ansible.builtin.command: "localectl set-locale LANG={{ locales|first }}"
  when: locale.changed
