- name: system setup | memory | adjust current swappiness
  tags: swappiness,sysctl,system,setup
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present

- name: system setup | memory | install earlyoom package
  tags: earlyoom,packages,system,setup
  ansible.builtin.package:
    name: earlyoom
    state: latest

- name: system setup | memory | enable and start earlyoom
  tags: earlyoom,packages,system,setup
  ansible.builtin.service:
    name: earlyoom
    enabled: yes
    state: started
