- name: system setup | microcode | install package
  tags: amd,intel,cpu,microcode,system setup
  ansible.builtin.package:
    name: "{{ (microcode_install == 'amd') | ternary(amd_microcode_package, intel_microcode_package) }}"
  when:
    - microcode_install is defined
    - microcode_install in ["amd", "intel"]
